### ISSUE TITLE
clr-installer: 2.3.1: "no such file or directory" error when mounting rootfs, so unable to install Clear Linux from live-server image

### ISSUE THREAD

**Issue by thac0** [clearlinux/clr-installer#588]
**Describe the bug**
While attempting to install 31310 from the live-server image from the console, I am not able to install Clear Linux because clr-installer errors out with a "no such file or directory" when attempting to mount the rootfs.

**To Reproduce**
1. Boot live-server image
2. As root, run "clr-installer"
3. Attempt a destructive installation on an NVME target (also reproducible if attempting to install from a --config YAML)
4. Begin installation
5. See error when clr-installer attempts to mount rootfs

**Expected behavior**
Clear Linux installs normally, from TUI interface or from a --config YAML.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Clear Linux OS Version: 31310
 - Installer Version 2.3.1
 - Platform: Dell XPS 13 9380

**Additional context**
N/A

**Comment by thac0** [comment]
Snippet from pre-install-clr-installer.yaml:
```
targetMedia:
- name: nvme0n1
  size: "0"
  ro: "false"
  rm: "false"
  type: disk
  children:
  - name: nvme0n1p1
    fstype: vfat
    mountpoint: /boot
    label: boot
    size: "524288000"
    ro: "false"
    rm: "false"
    type: part
  - name: nvme0n1p2
    fstype: swap
    label: swap
    size: "8589934592"
    ro: "false"
    rm: "false"
    type: part
  - name: nvme0n1p3
    fstype: xfs
    mountpoint: /
    label: root
    size: "0"
    ro: "false"
    rm: "false"
    type: part
```

Snippet from clr-installer.log:
```
[snip]
2019/10/16 15:52:41 [INF] Mounting: /
2019/10/16 15:52:41 [DBG] telem-record-gen [snip]
mount /dev/nvme0n1p3 /tmp/install-822812093 xfs: no such file or directory

Error Trace:
storage.mountFs()
     storage/ops.go:965
storage.(*BlockDevice).Mount()
     storage/ops.go:178
[snip]
```
