### ISSUE TITLE
Enable gocritic linter

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#717]
Enable the gocritic linter for golangci-lint and fix the flagged issues.

We should consider these settings when implementing:
```YAML
gocritic:
  enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style
  disabled-checks:
    - dupImport # https://github.com/go-critic/go-critic/issues/845
    - ifElseChain
    - octalLiteral
    - whyNoLint
    - wrapperFunc
```

The output of this all seems reasonable and worth implementing.
Many of these may be overlapped with Enable gosimple linter #714
