### ISSUE TITLE
[fail] Mount /dev/nume0n1p8 /tmp/install-425975728 ext4: no such file or directory

### ISSUE THREAD

**Issue by MarsOrBust24** [clearlinux/clr-installer#780]
**Describe the bug**
Installer failed to find the newly created ext4 parition. Using Manjaro I was able to see that it existed, but was completely empty. another possibility is that the `/tmp/install-425975728` mount point did not exist.

**To Reproduce**
1. Try to install Clear Linux on an Asus UX8402
2. Use the TUI and get to the Installation media screen
3. Use the included partition editor to delete a 256GB partition
4. Select safe installation mode and choose the main NVME drive

**Screenshots**
![PXL_20220828_195529500 MP](https://user-images.githubusercontent.com/876076/187094081-283d2555-e2bf-4312-8624-67ed722ed4b6.jpg)

**Environment (please complete the following information):**
 - Clear Linux OS Version: Latest 2022-08-29
 - Installer Version Latest 2022-08-29
 - Platform: 12th Gen Intel(R) Core(TM) i7-12700H ASUS UX8402ZA

**Additional context**
It created an EFI partition and an EXT4 partition... but the partition was empty when I looked at it with another distro. This may be a race condition.

<details>
<summary>Error screen</summary>

The Installer will now exit.
mount /dev/nume0n1p8 /tmp/install-425975728 ext4: no such file or directory

Error Trace:
storage mountFs (
/builddir/build/BUILD/clr-installer-2.7.3/storage/utils.go:34 storage, (BlockDevice).Mount()
/builddir/build/BUILD/clr-installer-2.7.3/storage/block_devices_ops.go:283
clrlinux@clr-live"
</details>

**Comment by hajes** [comment]
same issue
`ls /tmp`

there is no `install-xxxxxxx` folder...thus nothing to mount

**Comment by udif** [comment]
same here, on 39930.
It seems that the /tmp mountpoint was not created.

**Comment by hajes** [comment]
I have found out that one must not play with with partitions, and simply let the installer work.

Custom partitions always resulted in failure in my case

**Comment by udif** [comment]
Yes, I found out myself too.

In my case I had a new disk, and I wanted only 500GB allocated, so I had to create another partition and leave an empty space in the desired size. More precisely, I created a 500GB partition on an empty disk, then another partition on the remaining disk space, and then erased the original 500GB partition, to leave an empty 500GB hole at the beginning of the disk.

I also found out that following the advice in https://github.com/clearlinux/clr-installer/issues/789 , calling `clr-install` or `clr-install-gui` with the `-c` flag and a previous configuration did not help (a segmentation fault error), and also caused an existing partition to be erased :-( Since that was an empty disk with empty partitions this was not a problem, but still should not happen.

**Comment by ThaDaVos** [comment]
I was running into the same issue when using a configuration file with below:
```yaml
block-devices:
  - name: bdevice
    file: /dev/nvme0n1

targetMedia:
  - name: ${bdevice}
    type: disk
    children:
      - name: ${bdevice}1
        fstype: vfat
        mountpoint: /boot
        size: "150M"
        type: part
      - name: ${bdevice}2
        fstype: swap
        size: "32M"
        type: part
      - name: ${bdevice}3
        fstype: ext4
        mountpoint: /
        size: "0"
        type: part
```

Funny thing - if you retry the installer right after, it works - so probably it's not waiting long enough and discarding an internal error somewhere
